import type { Metadata } from "next";
import { IranYekan } from "@/utils/fonts";
import "./globals.css";
import MainLayoutWrapper from "@/components/layout/MainLayoutWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={IranYekan.className}>{children}</body>
    </html>
  );
}
